/* webCAD - Estado inicial del documento | SPDX-License-Identifier: GPL-3.0-or-later */

export function createDocumentState(dependencies) {
  const {
    DEFAULT_LAYER,
    DEFAULT_LAYERS,
    DEFAULT_LINE_COLOR,
    DEFAULT_LINE_STYLE,
    DEFAULT_LINE_TYPE,
    DRAWING_PROFILES,
    SNAP_THRESHOLD,
    loadBooleanPreference,
    loadDimensionStylePreference,
    loadIntegerPreference,
    loadNavigationDevice,
    loadNumberPreference,
  } = dependencies;

  return {
    tool: 'select',
    pendingLineStart: null,
    polylineDraft: null,
    rectangleDraft: null,
    regularPolygonDraft: null,
    textDraft: null,
    hatchDraft: null,
    circleDraft: null,
    arcDraft: null,
    ellipseDraft: null,
    xlineDraft: null,
    tangentLineDraft: null,
    copyDraft: null,
    moveDraft: null,
    stretchDraft: null,
    polarArrayDraft: null,
    rotateDraft: null,
    scaleDraft: null,
    mirrorDraft: null,
    filletDraft: null,
    offsetDraft: null,
    chamferDraft: null,
    selectionSetDraft: null,
    eraseDraft: null,
    explodeDraft: null,
    extendDraft: null,
    blockCreateDraft: null,
    blockInsertDraft: null,
    blockEditDraft: null,
    dimensionDraft: null,
    imageDraft: null,
    imageCalibrationDraft: null,
    dimensionStyle: loadDimensionStylePreference(),
    dimensionPrecision: {
      engineering: {
        linear: loadIntegerPreference('webcad-dimension-linear-precision-engineering', 2, 0, 4),
        angular: loadIntegerPreference('webcad-dimension-angular-precision-engineering', 2, 0, 4),
      },
      architecture: {
        linear: loadIntegerPreference('webcad-dimension-linear-precision-architecture', 2, 0, 4),
        angular: loadIntegerPreference('webcad-dimension-angular-precision-architecture', 2, 0, 4),
      },
    },
    lastDimensionOffsets: {
      engineering: null,
      architecture: null,
    },
    filletRadii: {
      engineering: 10,
      architecture: 0.25,
    },
    offsetDistances: {
      engineering: loadNumberPreference('webcad-offset-distance-engineering', 10, SNAP_THRESHOLD),
      architecture: loadNumberPreference('webcad-offset-distance-architecture', 0.25, SNAP_THRESHOLD),
    },
    polarArrayCount: loadIntegerPreference('webcad-polar-array-count', 6, 2, 360),
    regularPolygonSides: loadIntegerPreference('webcad-regular-polygon-sides', 6, 3, 360),
    chamferDistances: {
      engineering: { first: 10, second: 10 },
      architecture: { first: 0.25, second: 0.25 },
    },
    lastCopy: null,
    drawingProfile: 'engineering',
    navigationDevice: loadNavigationDevice(),
    lastTextHeight: DRAWING_PROFILES.engineering.defaultTextHeight,
    previousSelection: [],
    mouseWorld: null,
    mouseScreen: null,
    viewScale: 1,
    viewOffset: { x: 0, y: 0 },
    snapEnabled: loadBooleanPreference('webcad-grid-enabled', true),
    orthoEnabled: false,
    lineWeightDisplayEnabled: loadBooleanPreference('webcad-lineweight-display-enabled', true),
    distanceInput: '',
    selectedGrip: null,
    objectSnapEnabled: true,
    activeObjectSnap: null,
    activeInference: null,
    inferenceLock: null,
    hoveredEntity: null,
    snapPixelTolerance: 11,
    activeLineStyle: DEFAULT_LINE_STYLE,
    activeLineType: DEFAULT_LINE_TYPE,
    activeLineColor: DEFAULT_LINE_COLOR,
    layers: DEFAULT_LAYERS.map((layer) => ({ ...layer })),
    activeLayer: DEFAULT_LAYER.name,
    lastCommand: null,
    lastCircleTool: 'circle-center',
    lastArcTool: 'arc-center-start-end',
    doc: null,
    hasInitializedView: false,
    shiftKeyDown: false,
    statusText: 'Listo',
  };
}
