/*
 * webCAD - Catalogo de comandos
 * Copyright (C) 2026 Gonzalo Rodriguez
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

export const REPEATABLE_COMMANDS = new Set([
  'line',
  'tangent-line',
  'point-tangent-line',
  'xline',
  'polyline',
  'rectangle',
  'text',
  'hatch',
  'circle-center',
  'circle-3p',
  'arc-center-radius',
  'arc-3p',
  'arc-center-start-end',
  'ellipse',
  'dimension-horizontal',
  'dimension-vertical',
  'dimension-aligned',
  'dimension-angular',
  'dimension-radius',
  'dimension-diameter',
  'block-insert',
  'copy',
  'move',
  'stretch',
  'polar-array',
  'rotate',
  'scale',
  'mirror',
  'trim',
  'extend',
  'fillet',
  'offset',
  'chamfer',
  'erase',
  'explode',
]);

export function commandLabel(command) {
  const labels = {
    line: 'Linea',
    'tangent-line': 'Linea tangente',
    'point-tangent-line': 'Linea de punto a tangente a curva',
    xline: 'Linea infinita',
    polyline: 'Polilinea',
    rectangle: 'Rectangulo',
    text: 'Texto',
    hatch: 'Sombreado',
    'circle-center': 'Circulo centro-radio',
    'circle-3p': 'Circulo 3 puntos',
    'arc-center-radius': 'Arco centro-radio',
    'arc-3p': 'Arco 3 puntos',
    'arc-center-start-end': 'Arco centro-inicio-final',
    ellipse: 'Elipse',
    'block-create': 'Crear bloque',
    'block-insert': 'Insertar bloque',
    'dimension-horizontal': 'Cota horizontal',
    'dimension-vertical': 'Cota vertical',
    'dimension-aligned': 'Cota alineada',
    'dimension-angular': 'Cota angular',
    'dimension-radius': 'Cota de radio',
    'dimension-diameter': 'Cota de diametro',
    copy: 'Copiar',
    move: 'Desplazar',
    stretch: 'Estirar',
    'polar-array': 'Matriz polar',
    rotate: 'Girar',
    scale: 'Escala',
    mirror: 'Simetria',
    'select-set': 'Seleccionar conjunto',
    trim: 'Recortar',
    extend: 'Alargar',
    fillet: 'Empalme',
    offset: 'Equidistancia',
    chamfer: 'Chaflan',
    erase: 'Borrar',
    explode: 'Descomponer',
  };
  return labels[command] || 'Comando';
}
